---
- name: Perform yum update and reboot the server
  hosts: servers
  become: yes

  tasks:
    - name: Perform yum update
      yum:
        name: '*'
        state: latest
      notify: Reboot the server

  handlers:
    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible after yum update."
        pre_reboot_delay: 5
        post_reboot_delay: 30
        reboot_timeout: 300

