---
- name: Check if Node Exporter is running and start if not
  hosts: servers
  become: yes

  tasks:
    - name: Check if Node Exporter service is running
      shell: systemctl is-active node_exporter
      register: service_status
      failed_when: service_status.rc not in [0, 3]
      changed_when: false

    - name: Display Node Exporter status
      debug:
        msg: "Node Exporter is {{ service_status.stdout }}"

    - name: Start Node Exporter service if not running
      service:
        name: node_exporter
        state: started
      when: service_status.stdout != "active"

