---
- name: Reset user password
  hosts: all
  become: yes
  vars_prompt:
    - name: "username"
      prompt: "Enter the username to reset the password"
      private: no
    - name: "new_password"
      prompt: "Enter the new password"
      private: yes
  tasks:
    - name: Check if user {{ username }} exists
      command: getent passwd {{ username }}
      register: user_exists
      ignore_errors: yes

    - name: Reset password for user {{ username }}
      user:
        name: "{{ username }}"
        password: "{{ new_password | password_hash('sha512') }}"
      when: user_exists.rc == 0

    - name: Notify if user {{ username }} does not exist
      debug:
        msg: "User {{ username }} does not exist"
      when: user_exists.rc != 0

